In [2]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier

In [3]:
df = pd.read_csv('train.csv')

In [4]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
df.drop(columns=['PassengerId','Name','Ticket','Cabin'],inplace=True)

In [6]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [7]:
# Step 1 -> train/test/split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['Survived']),
                                                 df['Survived'],
                                                 test_size=0.2,
                                                random_state=42)

In [8]:
X_train.head(2)

     Pclass   Sex   Age  SibSp  Parch  Fare Embarked
331       1  male  45.5      0      0  28.5        S
733       2  male  23.0      0      0  13.0        S

In [9]:
y_train.head()

331    0
733    0
382    0
704    0
813    0
Name: Survived, dtype: int64

In [10]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [11]:
# Applying imputation

si_age = SimpleImputer()
si_embarked = SimpleImputer(strategy='most_frequent')

X_train_age = si_age.fit_transform(X_train[['Age']])
X_train_embarked = si_embarked.fit_transform(X_train[['Embarked']])

X_test_age = si_age.transform(X_test[['Age']])
X_test_embarked = si_embarked.transform(X_test[['Embarked']])

In [13]:
X_train_age

array([[45.5       ],
       [23.        ],
       [32.        ],
       [26.        ],
       [ 6.        ],
       [24.        ],
       [45.        ],
       [29.        ],
       [29.49884615],
       [29.49884615],
       [42.        ],
       [36.        ],
       [33.        ],
       [17.        ],
       [29.        ],
       [50.        ],
       [35.        ],
       [38.        ],
       [34.        ],
       [17.        ],
       [11.        ],
       [61.        ],
       [30.        ],
       [ 7.        ],
       [63.        ],
       [20.        ],
       [29.49884615],
       [29.        ],
       [36.        ],
       [29.49884615],
       [50.        ],
       [27.        ],
       [30.        ],
       [33.        ],
       [29.49884615],
       [29.49884615],
       [ 2.        ],
       [25.        ],
       [51.        ],
       [25.        ],
       [29.49884615],
       [29.49884615],
       [24.        ],
       [18.        ],
       [29.49884615],
       [25.        ],
       [24.        ],
       [22.        ],
       [ 0.92      ],
       [24.        ],
       [26.        ],
       [34.        ],
       [21.        ],
       [29.49884615],
       [29.49884615],
       [29.49884615],
       [22.        ],
       [62.        ],
       [18.        ],
       [42.        ],
       [57.        ],
       [19.        ],
       [42.        ],
       [29.49884615],
       [20.        ],
       [34.5       ],
       [28.        ],
       [29.49884615],
       [23.        ],
       [22.        ],
       [52.        ],
       [30.        ],
       [36.5       ],
       [29.49884615],
       [22.        ],
       [50.        ],
       [27.        ],
       [22.        ],
       [51.        ],
       [36.        ],
       [29.        ],
       [22.        ],
       [50.        ],
       [40.        ],
       [27.        ],
       [29.49884615],
       [65.        ],
       [17.        ],
       [28.        ],
       [ 4.        ],
       [29.49884615],
       [ 1.        ],
       [36.        ],
       [43.        ],
       [38.        ],
       [31.        ],
       [29.        ],
       [18.        ],
       [29.49884615],
       [39.        ],
       [39.        ],
       [26.        ],
       [20.        ],
       [29.49884615],
       [49.        ],
       [23.        ],
       [ 1.        ],
       [29.49884615],
       [29.49884615],
       [ 3.        ],
       [ 4.        ],
       [19.        ],
       [40.5       ],
       [ 1.        ],
       [29.49884615],
       [21.        ],
       [54.        ],
       [29.49884615],
       [25.        ],
       [26.        ],
       [22.        ],
       [31.        ],
       [49.        ],
       [19.        ],
       [24.        ],
       [16.        ],
       [25.        ],
       [39.        ],
       [47.        ],
       [60.        ],
       [24.        ],
       [29.49884615],
       [27.        ],
       [29.49884615],
       [38.        ],
       [44.        ],
       [21.        ],
       [24.        ],
       [45.        ],
       [ 8.        ],
       [ 8.        ],
       [29.49884615],
       [32.        ],
       [50.        ],
       [21.        ],
       [50.        ],
       [23.        ],
       [32.        ],
       [29.49884615],
       [21.        ],
       [29.49884615],
       [25.        ],
       [15.        ],
       [31.        ],
       [25.        ],
       [54.        ],
       [28.        ],
       [38.        ],
       [41.        ],
       [33.        ],
       [52.        ],
       [16.        ],
       [20.        ],
       [ 9.        ],
       [29.49884615],
       [29.49884615],
       [29.49884615],
       [54.        ],
       [26.        ],
       [60.        ],
       [29.49884615],
       [44.        ],
       [20.        ],
       [29.49884615],
       [16.        ],
       [43.        ],
       [17.        ],
       [37.        ],
       [62.        ],
       [ 8.        ],
       [32.        ],
       [20.        ],
       [28.        ],
       [21.        ],
       [37.        ],
       [17.        ],
       [29.49884615],
       [46.        ],
       [29.49884615],
       [24.        ],
       [29.        ],
       [56.        ],
       [31.        ],
       [29.49884615],
       [32.        ],
       [33.        ],
       [59.        ],
       [58.        ],
       [29.49884615],
       [ 3.        ],
       [29.49884615],
       [16.        ],
       [45.        ],
       [43.        ],
       [30.        ],
       [28.5       ],
       [24.        ],
       [30.        ],
       [36.        ],
       [25.        ],
       [29.49884615],
       [50.        ],
       [ 0.75      ],
       [24.        ],
       [24.        ],
       [35.        ],
       [30.        ],
       [23.        ],
       [29.49884615],
       [27.        ],
       [55.        ],
       [35.        ],
       [29.49884615],
       [29.49884615],
       [29.49884615],
       [23.        ],
       [29.49884615],
       [23.        ],
       [51.        ],
       [33.        ],
       [29.        ],
       [29.49884615],
       [29.49884615],
       [ 2.        ],
       [14.        ],
       [54.        ],
       [15.        ],
       [22.        ],
       [27.        ],
       [29.49884615],
       [29.49884615],
       [28.        ],
       [39.        ],
       [ 2.        ],
       [24.        ],
       [32.        ],
       [45.5       ],
       [ 8.        ],
       [26.        ],
       [29.        ],
       [45.        ],
       [36.        ],
       [29.49884615],
       [ 4.        ],
       [16.        ],
       [58.        ],
       [40.5       ],
       [25.        ],
       [29.49884615],
       [51.        ],
       [29.49884615],
       [17.        ],
       [29.49884615],
       [40.        ],
       [25.        ],
       [47.        ],
       [29.49884615],
       [44.        ],
       [23.        ],
       [18.        ],
       [29.        ],
       [12.        ],
       [11.        ],
       [22.        ],
       [19.        ],
       [22.        ],
       [33.        ],
       [56.        ],
       [ 1.        ],
       [22.        ],
       [29.49884615],
       [29.49884615],
       [ 7.        ],
       [ 4.        ],
       [70.5       ],
       [18.        ],
       [20.        ],
       [24.        ],
       [29.49884615],
       [34.        ],
       [29.49884615],
       [31.        ],
       [30.        ],
       [18.        ],
       [ 9.        ],
       [39.        ],
       [33.        ],
       [70.        ],
       [24.        ],
       [58.        ],
       [21.        ],
       [17.        ],
       [28.        ],
       [24.        ],
       [29.49884615],
       [29.49884615],
       [42.        ],
       [18.        ],
       [ 2.        ],
       [34.        ],
       [ 3.        ],
       [58.        ],
       [32.        ],
       [31.        ],
       [29.49884615],
       [27.        ],
       [11.        ],
       [23.        ],
       [40.        ],
       [29.49884615],
       [28.        ],
       [28.        ],
       [29.49884615],
       [19.        ],
       [30.        ],
       [20.        ],
       [28.        ],
       [36.        ],
       [29.49884615],
       [24.        ],
       [28.5       ],
       [24.        ],
       [42.        ],
       [54.        ],
       [25.        ],
       [ 7.        ],
       [25.        ],
       [27.        ],
       [24.        ],
       [29.49884615],
       [28.        ],
       [19.        ],
       [22.        ],
       [29.49884615],
       [29.49884615],
       [42.        ],
       [50.        ],
       [ 3.        ],
       [29.49884615],
       [18.        ],
       [18.        ],
       [44.        ],
       [29.49884615],
       [29.49884615],
       [29.49884615],
       [16.        ],
       [29.49884615],
       [22.        ],
       [ 4.        ],
       [29.49884615],
       [24.        ],
       [30.        ],
       [29.        ],
       [24.        ],
       [45.        ],
       [32.        ],
       [21.        ],
       [35.        ],
       [29.49884615],
       [29.49884615],
       [36.        ],
       [41.        ],
       [23.        ],
       [34.        ],
       [29.49884615],
       [29.49884615],
       [15.        ],
       [29.49884615],
       [18.        ],
       [30.        ],
       [32.        ],
       [ 4.        ],
       [ 2.        ],
       [29.49884615],
       [29.49884615],
       [48.        ],
       [31.        ],
       [47.        ],
       [26.        ],
       [ 9.        ],
       [19.        ],
       [29.49884615],
       [22.        ],
       [29.49884615],
       [28.        ],
       [24.        ],
       [17.        ],
       [29.49884615],
       [29.49884615],
       [21.        ],
       [51.        ],
       [ 3.        ],
       [ 0.75      ],
       [29.49884615],
       [34.        ],
       [18.        ],
       [44.        ],
       [29.49884615],
       [29.49884615],
       [37.        ],
       [21.        ],
       [36.        ],
       [32.        ],
       [29.49884615],
       [26.        ],
       [80.        ],
       [55.5       ],
       [60.        ],
       [29.49884615],
       [18.        ],
       [14.5       ],
       [19.        ],
       [ 4.        ],
       [33.        ],
       [21.        ],
       [10.        ],
       [47.        ],
       [ 2.        ],
       [29.        ],
       [22.        ],
       [28.        ],
       [29.49884615],
       [26.        ],
       [33.        ],
       [27.        ],
       [27.        ],
       [34.        ],
       [29.49884615],
       [30.        ],
       [30.        ],
       [29.49884615],
       [29.49884615],
       [53.        ],
       [32.        ],
       [52.        ],
       [52.        ],
       [39.        ],
       [ 2.        ],
       [44.        ],
       [51.        ],
       [39.        ],
       [46.        ],
       [17.        ],
       [30.        ],
       [ 9.        ],
       [27.        ],
       [21.        ],
       [29.49884615],
       [26.        ],
       [ 3.        ],
       [48.        ],
       [36.        ],
       [29.49884615],
       [32.5       ],
       [33.        ],
       [22.        ],
       [19.        ],
       [74.        ],
       [42.        ],
       [40.        ],
       [35.        ],
       [24.        ],
       [39.        ],
       [32.5       ],
       [ 1.        ],
       [34.        ],
       [64.        ],
       [25.        ],
       [29.49884615],
       [ 1.        ],
       [45.        ],
       [31.        ],
       [21.        ],
       [25.        ],
       [15.        ],
       [26.        ],
       [30.        ],
       [24.        ],
       [35.        ],
       [70.        ],
       [29.49884615],
       [21.        ],
       [18.        ],
       [29.49884615],
       [ 1.        ],
       [29.49884615],
       [26.        ],
       [25.        ],
       [29.49884615],
       [20.        ],
       [54.        ],
       [22.        ],
       [59.        ],
       [54.        ],
       [27.        ],
       [31.        ],
       [22.        ],
       [33.        ],
       [ 6.        ],
       [ 5.        ],
       [39.        ],
       [24.5       ],
       [54.        ],
       [29.49884615],
       [29.49884615],
       [30.        ],
       [29.49884615],
       [35.        ],
       [21.        ],
       [32.        ],
       [16.        ],
       [22.        ],
       [29.49884615],
       [38.        ],
       [29.49884615],
       [25.        ],
       [33.        ],
       [29.49884615],
       [18.        ],
       [29.49884615],
       [29.49884615],
       [ 2.        ],
       [ 0.42      ],
       [26.        ],
       [41.        ],
       [48.        ],
       [48.        ],
       [48.        ],
       [ 4.        ],
       [39.        ],
       [33.        ],
       [29.        ],
       [49.        ],
       [29.49884615],
       [29.49884615],
       [42.        ],
       [36.        ],
       [61.        ],
       [18.        ],
       [18.        ],
       [ 0.67      ],
       [32.        ],
       [29.49884615],
       [29.49884615],
       [29.49884615],
       [16.        ],
       [31.        ],
       [48.        ],
       [22.        ],
       [13.        ],
       [32.        ],
       [28.        ],
       [46.        ],
       [28.        ],
       [42.        ],
       [35.        ],
       [ 2.        ],
       [31.        ],
       [29.49884615],
       [29.49884615],
       [19.        ],
       [20.        ],
       [14.        ],
       [34.        ],
       [29.49884615],
       [29.49884615],
       [51.        ],
       [29.49884615],
       [29.49884615],
       [29.49884615],
       [28.        ],
       [25.        ],
       [19.        ],
       [35.        ],
       [35.        ],
       [ 9.        ],
       [20.        ],
       [42.        ],
       [30.        ],
       [29.49884615],
       [21.        ],
       [47.        ],
       [25.        ],
       [16.        ],
       [45.        ],
       [38.        ],
       [56.        ],
       [29.49884615],
       [31.        ],
       [30.        ],
       [29.49884615],
       [14.        ],
       [16.        ],
       [40.        ],
       [55.        ],
       [19.        ],
       [45.        ],
       [36.        ],
       [27.        ],
       [49.        ],
       [41.        ],
       [19.        ],
       [33.        ],
       [27.        ],
       [29.49884615],
       [35.        ],
       [29.        ],
       [30.        ],
       [34.        ],
       [29.        ],
       [19.        ],
       [35.        ],
       [29.49884615],
       [40.        ],
       [62.        ],
       [25.        ],
       [26.        ],
       [18.        ],
       [34.        ],
       [48.        ],
       [28.        ],
       [24.        ],
       [17.        ],
       [38.        ],
       [29.49884615],
       [40.        ],
       [22.        ],
       [ 2.        ],
       [28.        ],
       [18.        ],
       [28.        ],
       [19.        ],
       [29.49884615],
       [60.        ],
       [20.        ],
       [45.        ],
       [29.49884615],
       [24.        ],
       [29.49884615],
       [29.49884615],
       [39.        ],
       [26.        ],
       [24.        ],
       [36.        ],
       [37.        ],
       [29.49884615],
       [28.        ],
       [19.        ],
       [43.        ],
       [25.        ],
       [47.        ],
       [16.        ],
       [ 0.83      ],
       [22.        ],
       [19.        ],
       [28.        ],
       [14.        ],
       [36.        ],
       [29.        ],
       [42.        ],
       [29.49884615],
       [27.        ],
       [29.        ],
       [ 5.        ],
       [22.        ],
       [29.49884615],
       [30.        ],
       [62.        ],
       [34.        ],
       [28.        ],
       [29.49884615],
       [44.        ],
       [45.        ],
       [19.        ],
       [18.        ],
       [31.        ],
       [29.49884615],
       [21.        ],
       [25.        ],
       [32.        ],
       [30.        ],
       [40.        ],
       [33.        ],
       [36.        ],
       [47.        ],
       [34.        ],
       [19.        ],
       [29.49884615],
       [50.        ],
       [29.49884615],
       [29.49884615],
       [29.49884615],
       [29.49884615],
       [35.        ],
       [35.        ],
       [18.        ],
       [16.        ],
       [21.        ],
       [29.49884615],
       [41.        ],
       [14.        ],
       [21.        ]])

In [14]:
# one hot encoding Sex and Embarked

ohe_sex = OneHotEncoder(sparse=False,handle_unknown='ignore')
ohe_embarked = OneHotEncoder(sparse=False,handle_unknown='ignore')

X_train_sex = ohe_sex.fit_transform(X_train[['Sex']])
X_train_embarked = ohe_embarked.fit_transform(X_train_embarked)

X_test_sex = ohe_sex.transform(X_test[['Sex']])
X_test_embarked = ohe_embarked.transform(X_test_embarked)

In [15]:
X_train_embarked

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [16]:
X_train.head(2)

     Pclass   Sex   Age  SibSp  Parch  Fare Embarked
331       1  male  45.5      0      0  28.5        S
733       2  male  23.0      0      0  13.0        S

In [17]:
X_train_rem = X_train.drop(columns=['Sex','Age','Embarked'])

In [18]:
X_test_rem = X_test.drop(columns=['Sex','Age','Embarked'])

In [19]:
X_train_transformed = np.concatenate((X_train_rem,X_train_age,X_train_sex,X_train_embarked),axis=1)
X_test_transformed = np.concatenate((X_test_rem,X_test_age,X_test_sex,X_test_embarked),axis=1)

In [23]:
X_train_transformed.shape

(712, 10)

In [24]:
clf = DecisionTreeClassifier()
clf.fit(X_train_transformed,y_train)

DecisionTreeClassifier()

In [25]:
y_pred = clf.predict(X_test_transformed)
y_pred

array([0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1], dtype=int64)

In [27]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test)

0.7932960893854749

In [28]:
import pickle

In [30]:
pickle.dump(ohe_sex,open('models/ohe_sex.pkl','wb'))
pickle.dump(ohe_embarked,open('models/ohe_embarked.pkl','wb'))
pickle.dump(clf,open('models/clf.pkl','wb'))# this three files will be stored in the model folder